-- Run this first:
INSERT INTO SURVEYS (SurveyName) VALUES ('MainSurvey');
-- Should make surveyID 1 as its auto increment

-- SurveyID, QuestionNumber, QuestionType, Question, PK (SurveyID, QuestionNumber), FK (surveyID) references Surveys(SurveyID) on DELETE CASCADE
INSERT INTO QUESTIONS (SurveyID, QuestionNumber, QuestionType, Question) VALUES
(1, 1, 'Yes/No', 'Have you ever compared yourself to another person?'),
(1, 2, 'Yes/No', 'Have you ever not gone to an event, meal, or activity because you had no one to go with?'),
(1, 3, 'Yes/No', 'Have you ever intentionally skipped meals or starved yourself?'),
(1, 4, 'Yes/No', 'Have you ever seen a professional counselor?'),
(1, 5, 'Yes/No', 'Have you ever been physically and/or sexually abused?'),
(1, 6, 'Yes/No', 'Have you ever been verbally and/or emotionally abused?'),
(1, 7, 'Yes/No', 'Have you ever experienced anxiety that inhibits daily functioning?'),
(1, 8, 'Yes/No', 'Have you ever consumed alcohol as a response to stress or had "too much" to drink?'),
(1, 9, 'Yes/No', 'Have you participated in sexual activity through texting, Snapchat, or other technology?'),
(1, 10, 'Yes/No', 'Have you ever voluntarily crossed a physical boundary or gone further than you wanted to in an intimate relationship (Oral Sex or Touching that was beyond your boundaries)?'),
(1, 11, 'Yes/No', 'Have you ever struggled with viewing pornography or reading erotic media?'),
(1, 12, 'Yes/No', 'Have you or any of your family members been diagnosed with a mental illness?'),
(1, 13, 'Yes/No', 'Have you ever heard a comment on IWU''s campus that discriminates against a specific gender, either directed at you or someone else?'),
(1, 14, 'Yes/No', 'Have you ever been fearful of being perceived as weak?'),
(1, 15, 'Yes/No', 'Have you ever been taken advantage of by a person of authority?'),
(1, 16, 'Yes/No', 'Have you ever felt that you didn''t fit the cultural definition of masculinity/femininity?'),
(1, 17, 'Yes/No', 'Have you ever struggled with masturbation?'),
(1, 18, 'Yes/No', 'Have you ever said no to a social opportunity because of not having the money to participate?'),
(1, 19, 'Yes/No', 'Have you ever experienced prolonged seasons of feeling depressed?'),
(1, 20, 'Yes/No', 'Have you experienced divorce or separation in your family?'),
(1, 21, 'Yes/No', 'Have you ever had a difficult time trusting God?'),
(1, 22, 'Yes/No', 'Have you ever heard attacking or abusive comments on IWU''s campus regarding a person''s sexual orientation, either directed at you or someone else?'),
(1, 23, 'Yes/No', 'Have you ever struggled to make friends or feel like you belong in your friend group?'),
(1, 24, 'Yes/No', 'Have you ever felt "lost" or spiritually marginalized in a Christian environment?'),
(1, 25, 'Yes/No', 'Have you ever felt your political opinions didn''t have a place at IWU or in your community?'),
(1, 26, 'Yes/No', 'Have you ever used tobacco products, smoking devices, illegal drugs, or prescription drugs (not as prescribed) as a response to stress?'),
(1, 27, 'Yes/No', 'Have you ever had sexual intercourse outside of marriage?'),
(1, 28, 'Yes/No', 'Have you ever heard a comment on IWU''s campus that discriminates against a specific race or ethnicity, either directed at you or someone else?'),
(1, 29, 'Yes/No', 'Have you ever been sexually assaulted or harassed?'),
(1, 30, 'Yes/No', 'Have you ever had suicidal thoughts?'),
(1, 31, 'Yes/No', 'Have you ever avoided professional counseling due to fear of stigma?'),
(1, 32, 'Yes/No', 'Have you ever worked out excessively?'),
(1, 33, 'Yes/No', 'Have you ever intentionally hurt yourself (i.e. cutting, burning, scratching, etc.)?'),
(1, 34, 'Yes/No', 'Have you ever felt like you do not belong here at IWU?'),
(1, 35, 'Yes/No', 'Have you experienced jealousy over another''s relationship?'),
(1, 36, 'Yes/No', 'Have you, a family member, relative, or close friend been arrested or incarcerated?'),
(1, 37, 'Yes/No', 'Have you avoided sharing or choosing political views because of fear of how someone might respond?'),
(1, 38, 'Yes/No', 'Have you ever experienced bullying or cyberbullying?'),
(1, 39, 'Yes/No', 'Have you ever felt like God could not love you or forgive you?'),
(1, 40, 'Yes/No', 'Have you ever kept any of the above topics to yourself (told no one)?'),
(1, 41, 'Yes/No', 'Have you ever lied about any of these topics because you were afraid of being judged?'),
(1, 42, 'Yes/No', 'Have you ever felt ashamed about your lack of experience in any of these topics?'),
(1, 43, 'Yes/No', 'Have you ever felt you could not forgive yourself or another regarding one of these topics?'),
(1, 44, 'Yes/No', 'Have you ever felt alone in any of these topics?');
